//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAssessmentLogDto
    {
        public int Id { get; set; }
        public int DealId { get; set; }
        public string LegalEntity { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> AssessmentUser { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> EffectiveUser { get; set; }
        public string Version { get; set; }
    }
}
