//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactHistory
    {
        public int Id { get; set; }
        public string LegalEntity { get; set; }
        public string CustomerNum { get; set; }
        public string ContactType { get; set; }
        public string CollectorId { get; set; }
        public string ContacterId { get; set; }
        public System.DateTime ContactDate { get; set; }
        public string Comments { get; set; }
        public string Deal { get; set; }
        public Nullable<int> AlertId { get; set; }
        public string ContactId { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdatePerson { get; set; }
        public string SiteUseId { get; set; }
        public Nullable<bool> IsCostomerContact { get; set; }
        public string Region { get; set; }
        public string ToTitle { get; set; }
        public string ToName { get; set; }
        public string CCTitle { get; set; }
    }
}
