//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactor
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string CustomerNum { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string Number { get; set; }
        public string EmailAddress { get; set; }
        public string LivingAddress { get; set; }
        public string Country { get; set; }
        public string CommunicationLanguage { get; set; }
        public string IsDefaultFlg { get; set; }
        public string Comment { get; set; }
        public string LegalEntity { get; set; }
        public string ToCc { get; set; }
        public string GroupCode { get; set; }
        public string BkCustomerNum { get; set; }
        public string SiteUseId { get; set; }
        public Nullable<bool> IsCostomerContact { get; set; }
    }
}
