//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLevelView
    {
        public int Id { get; set; }
        public string CustomerNum { get; set; }
        public string Deal { get; set; }
        public Nullable<decimal> Class { get; set; }
        public string ClassLevel { get; set; }
        public Nullable<decimal> Risk { get; set; }
        public string RiskLevel { get; set; }
        public string SiteUseId { get; set; }
    }
}
