//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentBank
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string CustomerNum { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string Flg { get; set; }
        public string CreatePersonId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Description { get; set; }
        public string LegalEntity { get; set; }
        public string SiteUseId { get; set; }
    }
}
