//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGroupCfg
    {
        public CustomerGroupCfg()
        {
            this.Custmer = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string Deal { get; set; }
        public string BillGroupCode { get; set; }
        public string BillGroupName { get; set; }
        public string Collector { get; set; }
        public string CollectorName { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<Customer> Custmer { get; set; }
    }
}
