//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMasterView
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string CustomerNum { get; set; }
        public string CustomerName { get; set; }
        public string CusStatus { get; set; }
        public string BillGroupCode { get; set; }
        public string BillGroupName { get; set; }
        public string Operator { get; set; }
        public string Contact { get; set; }
        public string IsHoldFlg { get; set; }
        public string Existcont { get; set; }
    }
}
