//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerChangeHis
    {
        public int Id { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public string Deal { get; set; }
        public string CustomerNum { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string ValueLevel { get; set; }
        public string VrType { get; set; }
        public string VrDesc { get; set; }
    }
}
