//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPrioritizationExceptionList
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string CustomerNum { get; set; }
        public string ExType { get; set; }
        public string ExValue { get; set; }
        public System.DateTime EffectDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Desciption { get; set; }
    }
}
