//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMasterData
    {
        public string Deal { get; set; }
        public string CustomerNum { get; set; }
        public string CustomerName { get; set; }
        public string BillGroupCode { get; set; }
        public string BillGroupName { get; set; }
        public string IsHoldFlg { get; set; }
        public string SpecialNotes { get; set; }
        public string Comment { get; set; }
        public string Collector { get; set; }
        public string Class { get; set; }
        public int Id { get; set; }
        public string FlgName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Country { get; set; }
        public string ExcludeFlg { get; set; }
        public string IsIc { get; set; }
        public string CollectorName { get; set; }
        public string PARTY_TYPE { get; set; }
        public string PARTY_NUMBER { get; set; }
        public string TERRITORY_NAME { get; set; }
        public string SITE_NO { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string STATUS { get; set; }
        public string SITE_USE_CODE { get; set; }
        public string LOCALIZE_CUSTOMER_NAME { get; set; }
        public string PARTY_SITE_NAME { get; set; }
        public string ALTERNATE_NAME { get; set; }
        public string TRANSLATED_CUSTOMER_NAME { get; set; }
        public string SiteUseId { get; set; }
        public string CREDIT_TREM { get; set; }
        public string Organization { get; set; }
        public string LSR { get; set; }
        public string FSR { get; set; }
        public string CUSTOMER_SERVICE { get; set; }
        public string CONTACT_LANGUAGE { get; set; }
        public Nullable<bool> IsAMS { get; set; }
        public string SALES1 { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public Nullable<decimal> AMTLimit { get; set; }
        public string Ebname { get; set; }
        public string SoaTemplete { get; set; }
        public string Region { get; set; }
        public Nullable<int> star { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string GroupName { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> BadDebt { get; set; }
        public string Litigation { get; set; }
        public Nullable<System.DateTime> CommentExpirationDate { get; set; }
        public Nullable<System.DateTime> PTPDATE { get; set; }
        public Nullable<decimal> PTPAMOUNT { get; set; }
        public Nullable<System.DateTime> CommentLastDate { get; set; }
    }
}
