//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTC.POC.Repository.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerStaing
    {
        public int Id { get; set; }
        public string CustomerNum { get; set; }
        public string CustomerName { get; set; }
        public string Deal { get; set; }
        public Nullable<decimal> OneYearSales { get; set; }
        public string ImportId { get; set; }
        public string VClass { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
