//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DunningReminderConfig
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string VRClass { get; set; }
        public string CustomerNum { get; set; }
        public Nullable<decimal> FirstInterval { get; set; }
        public Nullable<decimal> SecondInterval { get; set; }
        public Nullable<decimal> PaymentTAT { get; set; }
        public Nullable<decimal> RiskInterval { get; set; }
        public string Description { get; set; }
        public string LegalEntity { get; set; }
        public string SiteUseId { get; set; }
        public string Confirm1CommunicationMethod { get; set; }
        public Nullable<int> Confirm1Days { get; set; }
        public string Confirm2CommunicationMethod { get; set; }
        public Nullable<int> Confirm2Days { get; set; }
        public string RemindingCommunicationMethod { get; set; }
        public Nullable<int> RemindingDays { get; set; }
        public string Dunning1CommunicationMethod { get; set; }
        public Nullable<int> Dunning1Days { get; set; }
        public string Dunning2CommunicationMethod { get; set; }
        public Nullable<int> Dunning2Days { get; set; }
        public Nullable<bool> AutoSendConfirmPTP { get; set; }
        public Nullable<bool> AutoSendReminder { get; set; }
        public Nullable<bool> AutoSendDunning { get; set; }
        public string DunningRoundTableMethod { get; set; }
        public Nullable<int> DunningRoundTableDays { get; set; }
        public string Dispute2Method { get; set; }
        public Nullable<int> Dipsute2Days { get; set; }
        public string DisputeRoundTableMethod { get; set; }
        public Nullable<int> DisputeRoundTableDays { get; set; }
    }
}
