//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDownloadHistory
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public int PeriodId { get; set; }
        public string ImportId { get; set; }
        public string DownloadFileName { get; set; }
        public string DownloadFileFullname { get; set; }
        public string FileType { get; set; }
        public string ProcessFlag { get; set; }
        public string Operator { get; set; }
        public System.DateTime DownloadTime { get; set; }
        public string FileId { get; set; }
    }
}
