//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUploadHistory
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public string ImportId { get; set; }
        public string LegalEntity { get; set; }
        public string OriginalFileName { get; set; }
        public string ArchiveFileName { get; set; }
        public string FileType { get; set; }
        public Nullable<int> DataSize { get; set; }
        public string ProcessFlag { get; set; }
        public string SubmitFlag { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> ReportTime { get; set; }
        public System.DateTime UploadTime { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
    }
}
