//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAgingStaging
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string InvoiceNum { get; set; }
        public string InvoiceType { get; set; }
        public string CustomerNum { get; set; }
        public string CustomerName { get; set; }
        public string CreditTrem { get; set; }
        public string MstCustomer { get; set; }
        public string PoNum { get; set; }
        public string SoNum { get; set; }
        public string Class { get; set; }
        public string Currency { get; set; }
        public string States { get; set; }
        public string OrderBy { get; set; }
        public string BillGroupCode { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> OriginalAmt { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LegalEntity { get; set; }
        public string Operator { get; set; }
        public string ImportId { get; set; }
        public string Comments { get; set; }
        public string MissAccountFlg { get; set; }
        public string AttentionTo { get; set; }
        public string CollectorContact { get; set; }
        public string CollectorName { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerAddress3 { get; set; }
        public string CustomerAddress4 { get; set; }
        public string CustomerBillToSite { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerCountryDetail { get; set; }
        public Nullable<int> DaysLateSys { get; set; }
        public Nullable<decimal> OutstandingAccumulatedInvoiceAmt { get; set; }
        public string RboCode { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public string SiteUseId { get; set; }
        public Nullable<decimal> CreditLmt { get; set; }
        public Nullable<decimal> CreditLmtAcct { get; set; }
        public string SellingLocationCode { get; set; }
        public string CustomerService { get; set; }
        public string LsrNameHist { get; set; }
        public string Sales { get; set; }
        public string FsrNameHist { get; set; }
        public string FuncCurrCode { get; set; }
        public Nullable<decimal> WoVat_AMT { get; set; }
        public string AgingBucket { get; set; }
        public string CreditTremDescription { get; set; }
        public string SellingLocationCode2 { get; set; }
        public string Ebname { get; set; }
        public string Customertype { get; set; }
        public string Cmpinv { get; set; }
        public string Eb { get; set; }
        public string Fsr { get; set; }
        public string Assignment { get; set; }
        public string BillingNo { get; set; }
        public Nullable<decimal> RemainingAmtTran { get; set; }
        public string Internaltext { get; set; }
    }
}
