//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string Bussiness_Reference { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string BodyFormat { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Cc { get; set; }
        public string Attachment { get; set; }
        public string SavePath { get; set; }
        public string Operator { get; set; }
        public string CustomerAssignedFlg { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Type { get; set; }
        public string Collector { get; set; }
        public string MessageId { get; set; }
        public Nullable<long> InternalTime { get; set; }
        public Nullable<System.DateTime> InternalDatetime { get; set; }
        public string MailBox { get; set; }
        public string FileId { get; set; }
        public string RELATED_CUSTOMERS { get; set; }
    }
}
