//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailRaw
    {
        public int Id { get; set; }
        public string MessageId { get; set; }
        public Nullable<int> ProcessFlg { get; set; }
        public string ProcessError { get; set; }
        public Nullable<long> InternalTime { get; set; }
        public string FileId { get; set; }
        public string MailBox { get; set; }
        public string Deal { get; set; }
    }
}
