//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateTran
    {
        public int Id { get; set; }
        public string Currency { get; set; }
        public string ForeignCurrency { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string Deal { get; set; }
    }
}
