//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTC.POC.Repository.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int Id { get; set; }
        public string CustomerNum { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> RemindDate { get; set; }
        public string Language { get; set; }
        public Nullable<int> Round { get; set; }
        public string SentFlg { get; set; }
        public string Errors { get; set; }
    }
}
