//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskRule
    {
        public RiskRule()
        {
            this.RiskRuleIndex = new HashSet<RiskRuleIndex>();
        }
    
        public int Id { get; set; }
        public string Deal { get; set; }
        public string LegalEntity { get; set; }
        public int CalculateType { get; set; }
        public int CreatePersonId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<RiskRuleIndex> RiskRuleIndex { get; set; }
    }
}
