//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskRuleIndex
    {
        public int Id { get; set; }
        public int RuleId { get; set; }
        public string IndexName { get; set; }
        public int IndexRateMethod { get; set; }
        public int IndexWeighted { get; set; }
        public string Description { get; set; }
        public int IndexRateValue { get; set; }
    
        public virtual RiskRule RiskRule { get; set; }
    }
}
