//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sites
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string LegalEntity { get; set; }
        public string SiteNameSys { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Fax { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string AccountNoUsd { get; set; }
        public string AccountNoHkd { get; set; }
        public string Telephone { get; set; }
        public string SwiftCode { get; set; }
        public string Description { get; set; }
        public string Alia { get; set; }
        public string Stamp { get; set; }
    }
}
