//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartSoaAlertView
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string CustomerNum { get; set; }
        public string Collector { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<int> InvCount { get; set; }
        public int BatchType { get; set; }
        public string BillGroupCode { get; set; }
        public string GCode { get; set; }
        public Nullable<int> GCount { get; set; }
    }
}
