//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysConfig
    {
        public int Id { get; set; }
        public string CfgName { get; set; }
        public string CfgValue { get; set; }
        public string CfgValue2 { get; set; }
        public string CfgCode { get; set; }
        public string Deal { get; set; }
    }
}
