//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTypeDetail
    {
        public int Id { get; set; }
        public int Seq { get; set; }
        public string TypeCode { get; set; }
        public string DetailName { get; set; }
        public string DetailValue { get; set; }
        public string DetailValue2 { get; set; }
        public string DetailValue3 { get; set; }
        public string Description { get; set; }
    
        public virtual SysType SysType { get; set; }
    }
}
