//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ALLACCOUNT_TMP
    {
        public int Id { get; set; }
        public string LegalEntity { get; set; }
        public string CustomerNum { get; set; }
        public string CustomerName { get; set; }
        public string BillGroupCode { get; set; }
        public string BillGroupName { get; set; }
        public string Class { get; set; }
        public Nullable<decimal> ArBalanceAmtPeroid { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
        public Nullable<decimal> PaidAmt { get; set; }
        public Nullable<decimal> OverDue90Amt { get; set; }
        public Nullable<decimal> PtpAmt { get; set; }
        public Nullable<decimal> BrokenPTPAmt { get; set; }
        public Nullable<decimal> DisputeAmt { get; set; }
        public Nullable<decimal> UnapplidPayment { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string States { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PaymentTerm { get; set; }
        public Nullable<System.DateTime> SoaDate { get; set; }
        public Nullable<System.DateTime> SecondDate { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
        public string SpecialNotes { get; set; }
        public Nullable<decimal> AdjustedOver90 { get; set; }
        public string Collector { get; set; }
        public string Team { get; set; }
        public string Country { get; set; }
        public string Contact { get; set; }
        public string SiteUseId { get; set; }
        public string COLLECTOR_CONTACT { get; set; }
        public string CS { get; set; }
        public string Sales { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string CreditTremDescription { get; set; }
        public Nullable<decimal> TotalFutureDue { get; set; }
        public Nullable<decimal> PastDueAmount { get; set; }
        public string FinishedStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> AccountPtpAmount { get; set; }
    }
}
