//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AssessmentFactor
    {
        public T_AssessmentFactor()
        {
            this.T_CustomerScore = new HashSet<T_CustomerScore>();
        }
    
        public int Id { get; set; }
        public int DealId { get; set; }
        public string FactorName { get; set; }
        public int Algorithm { get; set; }
        public int Weight { get; set; }
        public bool IsDisabled { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationTime { get; set; }
        public long CreatorUserId { get; set; }
        public System.DateTime LastModificationTime { get; set; }
        public long LastModifierUserId { get; set; }
    
        public virtual T_Deal T_Deal { get; set; }
        public virtual ICollection<T_CustomerScore> T_CustomerScore { get; set; }
    }
}
