//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AssessmentType
    {
        public T_AssessmentType()
        {
            this.T_CustomerAssessment = new HashSet<T_CustomerAssessment>();
        }
    
        public int Id { get; set; }
        public int DealId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CollectionStrategyId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> CreatorUserId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<int> LastModifierUserId { get; set; }
        public bool IsDisabled { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<int> DunningPirority { get; set; }
    
        public virtual T_Deal T_Deal { get; set; }
        public virtual ICollection<T_CustomerAssessment> T_CustomerAssessment { get; set; }
    }
}
