//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COLLECTOR_STATISTICS_HIS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> STATISTICS_DATE { get; set; }
        public string STATISTICS_COLLECTOR { get; set; }
        public string STATISTICS_TYPE { get; set; }
        public Nullable<decimal> STATISTICS_VALUE { get; set; }
    }
}
