//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CustomerAssessment_Log
    {
        public T_CustomerAssessment_Log()
        {
            this.T_CustomerAssessment_History = new HashSet<T_CustomerAssessment_History>();
        }
    
        public int Id { get; set; }
        public int DealId { get; set; }
        public string LegalEntity { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> AssessmentUser { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> EffectiveUser { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<T_CustomerAssessment_History> T_CustomerAssessment_History { get; set; }
        public virtual T_Deal T_Deal { get; set; }
    }
}
