//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CustomerAssessment_History
    {
        public int Id { get; set; }
        public int Version { get; set; }
        public string CustomerId { get; set; }
        public string SiteUseId { get; set; }
        public decimal AssessmentScore { get; set; }
        public int AssessmentType { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public bool SyncStatus { get; set; }
        public Nullable<int> DealId { get; set; }
        public string LegalEntity { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual T_CustomerAssessment_Log T_CustomerAssessment_Log { get; set; }
    }
}
