//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CUSTOMER_AGING_DAYBACK
    {
        public int ID { get; set; }
        public System.DateTime BACK_DATE { get; set; }
        public int ID_TCUSTOMERAGING { get; set; }
        public string DEAL { get; set; }
        public string LEGAL_ENTITY { get; set; }
        public string CUSTOMER_NUM { get; set; }
        public string SiteUseId { get; set; }
        public Nullable<decimal> AR_BALANCE_PERIOD { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_CLASS { get; set; }
        public string RISK_SCORE { get; set; }
        public string BILL_GROUP_CODE { get; set; }
        public string BILL_GROUP_NAME { get; set; }
        public string COUNTRY { get; set; }
        public string CREDIT_TREM { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public string COLLECTOR { get; set; }
        public string COLLECTOR_SYS { get; set; }
        public string SALES { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public Nullable<decimal> CURRENT_AMT { get; set; }
        public Nullable<decimal> DUE15_AMT { get; set; }
        public Nullable<decimal> DUE30_AMT { get; set; }
        public Nullable<decimal> DUE45_AMT { get; set; }
        public Nullable<decimal> DUE60_AMT { get; set; }
        public Nullable<decimal> DUE90_AMT { get; set; }
        public Nullable<decimal> DUE120_AMT { get; set; }
        public Nullable<decimal> DUE150_AMT { get; set; }
        public Nullable<decimal> DUE180_AMT { get; set; }
        public Nullable<decimal> DUE210_AMT { get; set; }
        public Nullable<decimal> DUE240_AMT { get; set; }
        public Nullable<decimal> DUE270_AMT { get; set; }
        public Nullable<decimal> DUE300_AMT { get; set; }
        public Nullable<decimal> DUE330_AMT { get; set; }
        public Nullable<decimal> DUE360_AMT { get; set; }
        public Nullable<decimal> DUEOVER360_AMT { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public string IMPORT_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string IS_HOLD_FLG { get; set; }
        public Nullable<decimal> DUEOVER_TOTAL_AMT { get; set; }
        public string REMOVE_FLG { get; set; }
        public string CITY_OR_STATE { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> CUSTOMER_BALANCE { get; set; }
        public string CUSTOMER_CLAIMS { get; set; }
        public string CUSTOMER_CREDIT_MEMO { get; set; }
        public string CUSTOMER_PAYMENTS { get; set; }
        public string CUSTOMER_RECEIPTS_AT_RISK { get; set; }
        public Nullable<decimal> OUTSTANDING_AMT { get; set; }
        public string Ebname { get; set; }
        public Nullable<decimal> TotalFutureDue { get; set; }
        public string Comments { get; set; }
    }
}
