//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CustomerScore
    {
        public int Id { get; set; }
        public int DealId { get; set; }
        public string CustomerId { get; set; }
        public string SiteUseId { get; set; }
        public int FactorId { get; set; }
        public decimal FactorValue { get; set; }
        public decimal FactorScore { get; set; }
        public decimal SourceValue1 { get; set; }
        public Nullable<decimal> SourceValue2 { get; set; }
        public Nullable<decimal> SourceValue3 { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public int Version { get; set; }
        public string LegalEntity { get; set; }
    
        public virtual T_AssessmentFactor T_AssessmentFactor { get; set; }
        public virtual T_Deal T_Deal { get; set; }
    }
}
