//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Deal
    {
        public T_Deal()
        {
            this.T_AssessmentFactor = new HashSet<T_AssessmentFactor>();
            this.T_AssessmentStandards = new HashSet<T_AssessmentStandards>();
            this.T_AssessmentType = new HashSet<T_AssessmentType>();
            this.T_CollectionStrategy = new HashSet<T_CollectionStrategy>();
            this.T_CustomerAssessment = new HashSet<T_CustomerAssessment>();
            this.T_CustomerAssessment_Log = new HashSet<T_CustomerAssessment_Log>();
            this.T_CustomerScore = new HashSet<T_CustomerScore>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDIsabled { get; set; }
        public System.DateTime CreationTime { get; set; }
        public long CreatorUserId { get; set; }
        public System.DateTime LastModificationTIme { get; set; }
        public long LastModifierUserId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
    
        public virtual ICollection<T_AssessmentFactor> T_AssessmentFactor { get; set; }
        public virtual ICollection<T_AssessmentStandards> T_AssessmentStandards { get; set; }
        public virtual ICollection<T_AssessmentType> T_AssessmentType { get; set; }
        public virtual ICollection<T_CollectionStrategy> T_CollectionStrategy { get; set; }
        public virtual ICollection<T_CustomerAssessment> T_CustomerAssessment { get; set; }
        public virtual ICollection<T_CustomerAssessment_Log> T_CustomerAssessment_Log { get; set; }
        public virtual ICollection<T_CustomerScore> T_CustomerScore { get; set; }
    }
}
