//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_VAT
    {
        public int Id { get; set; }
        public string Trx_Number { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string SalesOrder { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CustomerTrxId { get; set; }
        public string AttributeCategory { get; set; }
        public string OrgId { get; set; }
        public string VATInvoice { get; set; }
        public string VATInvoiceDate { get; set; }
        public Nullable<decimal> VATInvoiceAmount { get; set; }
        public Nullable<decimal> VATTaxAmount { get; set; }
        public Nullable<decimal> VATInvoiceTotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
    }
}
