//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Invoice_Detail_Staging
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CustomerPO { get; set; }
        public string Manufacturer { get; set; }
        public string PartNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public int InvoiceLineNumber { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public Nullable<decimal> InvoiceQty { get; set; }
        public Nullable<decimal> UnitResales { get; set; }
        public Nullable<decimal> NSB { get; set; }
        public string Import_ID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> GPD { get; set; }
        public Nullable<decimal> Cost_Original { get; set; }
        public string CustomerPartNumber { get; set; }
    }
}
