//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_VARDATA
    {
        public int Id { get; set; }
        public string IDYear { get; set; }
        public string IDQQ { get; set; }
        public string IDMonth { get; set; }
        public string BillToCustomerOperatingUnit { get; set; }
        public string BillToCustomerOUName { get; set; }
        public string OrderNumber { get; set; }
        public string LineNumber { get; set; }
        public string VarData1 { get; set; }
        public string VarData2 { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceLineNumber { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> ExtendedResaleUSD { get; set; }
    }
}
