//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_STATUS_STAGING
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE_VAT { get; set; }
        public string INVOICE_NO_VAT { get; set; }
        public Nullable<decimal> INVOICE_AMOUNT_VAT { get; set; }
        public Nullable<decimal> INVOICE_AMOUNT_NOTAX { get; set; }
        public Nullable<decimal> INVOICE_TAXRATE { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<decimal> INVOICE_AMOUNT { get; set; }
        public string INVOICE_PAYTERM { get; set; }
        public Nullable<System.DateTime> INVOICE_DUEDATE { get; set; }
        public string INVOICE_ORDERNO { get; set; }
        public Nullable<System.DateTime> INVOICE_PTPDATE { get; set; }
        public string INVOICE_DISPUTE { get; set; }
        public string INVOICE_OTHER { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string INVOICE_CLASS { get; set; }
        public string IsForwarder { get; set; }
        public string Forwarder { get; set; }
        public string INVOICE_BalanceStatus { get; set; }
        public string INVOICE_BalanceMemo { get; set; }
        public string FILETYPE { get; set; }
        public string INVOICE_LineNo { get; set; }
        public string INVOICE_MaterialNo { get; set; }
        public Nullable<decimal> INVOICE_MaterialAmount { get; set; }
        public string INVOICE_CurrencyCode { get; set; }
        public string DueReason { get; set; }
        public string SiteUseId { get; set; }
        public string ConsignmentNumber { get; set; }
        public Nullable<System.DateTime> MemoExpirationDate { get; set; }
    }
}
