//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LeglalEB
    {
        public int Id { get; set; }
        public string LEGAL_ENTITY { get; set; }
        public string EB { get; set; }
        public string Collector { get; set; }
        public string Region { get; set; }
        public string CONTACT_LANGUAGE { get; set; }
        public string CREDIT_TREM { get; set; }
        public string CreditOfficer { get; set; }
        public string FinancialController { get; set; }
        public string CSManager { get; set; }
        public string FinancialManagers { get; set; }
        public string FinanceLeader { get; set; }
        public string LocalFinance { get; set; }
        public string BranchManager { get; set; }
        public string CollectorEmail { get; set; }
    }
}
