//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MailServer
    {
        public int Id { get; set; }
        public string MailDomain { get; set; }
        public string Address { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string ServerType { get; set; }
        public string Version { get; set; }
        public Nullable<int> SendPort { get; set; }
        public Nullable<int> ReceivePort { get; set; }
    }
}
