//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MD_EXCEPTIONS
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<long> EXCEPTIONS_TYPE { get; set; }
        public Nullable<long> RECURRENCE_PATTERN { get; set; }
        public Nullable<long> FREQUENCY { get; set; }
        public string FREQUENCY_WEEKS { get; set; }
        public Nullable<long> FREQUENCY_MONTH_DAY_EVERY { get; set; }
        public Nullable<long> FREQUENCY_MONTH_WEEK { get; set; }
        public Nullable<long> FREQUENCY_MONTH_WEEK_SEQUENCY { get; set; }
        public Nullable<long> FREQUENCY_MONTH { get; set; }
        public Nullable<long> FREQUENCY_MONTH_DAY_THE { get; set; }
        public string FREQUENCY_YEAR_DAY { get; set; }
        public Nullable<long> FREQUENCY_YEAR_WEEK { get; set; }
        public Nullable<long> FREQUENCY_YEAR_WEEK_SEQUENCY { get; set; }
        public Nullable<long> FREQUENCY_YEAR_MONTH { get; set; }
        public Nullable<System.DateTime> RANGE_START { get; set; }
        public Nullable<long> RANGE_END_AFTER { get; set; }
        public Nullable<System.DateTime> RANGE_END_BY { get; set; }
        public Nullable<long> RANGE_TYPE { get; set; }
        public Nullable<long> WORKINGCALENDAR_ID { get; set; }
        public Nullable<long> FREQUENCY_Daily_Number { get; set; }
    }
}
