//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ORG_REGION
    {
        public T_ORG_REGION()
        {
            this.T_ORG_CENTER = new HashSet<T_ORG_CENTER>();
            this.T_ORG_CENTER1 = new HashSet<T_ORG_CENTER>();
            this.T_ORG_DEAL = new HashSet<T_ORG_DEAL>();
            this.T_ORG_GROUP = new HashSet<T_ORG_GROUP>();
            this.T_USER_EMPLOYEE = new HashSet<T_USER_EMPLOYEE>();
            this.T_ORG_TEAM = new HashSet<T_ORG_TEAM>();
            this.T_USER_EMPLOYEE1 = new HashSet<T_USER_EMPLOYEE>();
        }
    
        public long ID { get; set; }
        public string REGION_NAME { get; set; }
        public Nullable<int> DEL_FLG { get; set; }
    
        public virtual ICollection<T_ORG_CENTER> T_ORG_CENTER { get; set; }
        public virtual ICollection<T_ORG_CENTER> T_ORG_CENTER1 { get; set; }
        public virtual ICollection<T_ORG_DEAL> T_ORG_DEAL { get; set; }
        public virtual ICollection<T_ORG_GROUP> T_ORG_GROUP { get; set; }
        public virtual ICollection<T_USER_EMPLOYEE> T_USER_EMPLOYEE { get; set; }
        public virtual ICollection<T_ORG_TEAM> T_ORG_TEAM { get; set; }
        public virtual ICollection<T_USER_EMPLOYEE> T_USER_EMPLOYEE1 { get; set; }
    }
}
