//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_LOG
    {
        public int ID { get; set; }
        public string LOG_LEVEL { get; set; }
        public string LOGGER { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string USER_ID { get; set; }
        public string REQUEST_URL { get; set; }
        public string TAG1 { get; set; }
        public string TAG2 { get; set; }
        public string TAG3 { get; set; }
        public string TAG4 { get; set; }
        public string EXCEPTION { get; set; }
    }
}
