//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TASK
    {
        public int ID { get; set; }
        public string DEAL { get; set; }
        public string LEGAL_ENTITY { get; set; }
        public string CUSTOMER_NUM { get; set; }
        public string SITEUSEID { get; set; }
        public Nullable<System.DateTime> TASK_DATE { get; set; }
        public string TASK_TYPE { get; set; }
        public string TASK_CONTENT { get; set; }
        public string TASK_STATUS { get; set; }
        public string ISAUTO { get; set; }
        public int CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
