//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_EMPLOYEE
    {
        public T_USER_EMPLOYEE()
        {
            this.T_USERS = new HashSet<T_USERS>();
            this.T_USERS1 = new HashSet<T_USERS>();
            this.T_USERS2 = new HashSet<T_USERS>();
        }
    
        public long ID { get; set; }
        public Nullable<long> DIRECT_MANAGER_ID { get; set; }
        public Nullable<int> USER_FLG { get; set; }
        public string USER_NAME { get; set; }
        public string USER_MAIL { get; set; }
        public string COUNTRY { get; set; }
        public string LOCATION { get; set; }
        public string DEAL { get; set; }
        public string VERTICAL { get; set; }
        public string TOWER { get; set; }
        public string PROCESS { get; set; }
        public string SUB_PROCESS { get; set; }
        public Nullable<long> REGION_ID { get; set; }
        public Nullable<long> CENTER_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> DEAL_ID { get; set; }
        public Nullable<long> TEAM_ID { get; set; }
        public Nullable<int> DEL_FLG { get; set; }
        public Nullable<int> DEFAULT_PORTAL { get; set; }
        public string AVATAR_URL { get; set; }
    
        public virtual T_ORG_CENTER T_ORG_CENTER { get; set; }
        public virtual T_ORG_CENTER T_ORG_CENTER1 { get; set; }
        public virtual T_ORG_DEAL T_ORG_DEAL { get; set; }
        public virtual T_ORG_GROUP T_ORG_GROUP { get; set; }
        public virtual T_ORG_REGION T_ORG_REGION { get; set; }
        public virtual T_ORG_REGION T_ORG_REGION1 { get; set; }
        public virtual T_ORG_TEAM T_ORG_TEAM { get; set; }
        public virtual ICollection<T_USERS> T_USERS { get; set; }
        public virtual ICollection<T_USERS> T_USERS1 { get; set; }
        public virtual ICollection<T_USERS> T_USERS2 { get; set; }
    }
}
