//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WF_DetailTask
    {
        public long Id { get; set; }
        public long ActivityId { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public long ProcessInstanceId { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public long TaskId { get; set; }
        public string TaskStatus { get; set; }
    }
}
