//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WF_Activity
    {
        public T_WF_Activity()
        {
            this.T_WF_Application = new HashSet<T_WF_Application>();
            this.T_WF_CurrentTask = new HashSet<T_WF_CurrentTask>();
            this.T_WF_HistoryTask = new HashSet<T_WF_HistoryTask>();
            this.T_WF_PostCondition = new HashSet<T_WF_PostCondition>();
            this.T_WF_PreCondition = new HashSet<T_WF_PreCondition>();
            this.T_WF_Webservice = new HashSet<T_WF_Webservice>();
        }
    
        public long Id { get; set; }
        public decimal Maxtime { get; set; }
        public string Memo { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Startmode { get; set; }
        public string Type { get; set; }
        public string SystemTypeTaskTypeID { get; set; }
        public Nullable<long> ProcessDefine_Id { get; set; }
    
        public virtual T_WF_ProcessDefine T_WF_ProcessDefine { get; set; }
        public virtual ICollection<T_WF_Application> T_WF_Application { get; set; }
        public virtual ICollection<T_WF_CurrentTask> T_WF_CurrentTask { get; set; }
        public virtual ICollection<T_WF_HistoryTask> T_WF_HistoryTask { get; set; }
        public virtual ICollection<T_WF_PostCondition> T_WF_PostCondition { get; set; }
        public virtual ICollection<T_WF_PreCondition> T_WF_PreCondition { get; set; }
        public virtual ICollection<T_WF_Webservice> T_WF_Webservice { get; set; }
    }
}
