//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WF_PostCondition
    {
        public long Id { get; set; }
        public string Condition { get; set; }
        public long TargetActivityId { get; set; }
        public Nullable<long> Activity_Id { get; set; }
        public string Message { get; set; }
    
        public virtual T_WF_Activity T_WF_Activity { get; set; }
    }
}
