//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WF_ProcessInstance
    {
        public T_WF_ProcessInstance()
        {
            this.T_WF_CurrentTask = new HashSet<T_WF_CurrentTask>();
            this.T_WF_HistoryTask = new HashSet<T_WF_HistoryTask>();
        }
    
        public long Id { get; set; }
        public string CauseObjectNumber { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string Status { get; set; }
        public Nullable<long> ProcessDefine_Id { get; set; }
    
        public virtual ICollection<T_WF_CurrentTask> T_WF_CurrentTask { get; set; }
        public virtual ICollection<T_WF_HistoryTask> T_WF_HistoryTask { get; set; }
        public virtual T_WF_ProcessDefine T_WF_ProcessDefine { get; set; }
    }
}
