//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WF_ProcessDefine
    {
        public T_WF_ProcessDefine()
        {
            this.T_WF_Activity = new HashSet<T_WF_Activity>();
            this.T_WF_ProcessInstance = new HashSet<T_WF_ProcessInstance>();
            this.T_WF_RelateData = new HashSet<T_WF_RelateData>();
        }
    
        public long Id { get; set; }
        public string Author { get; set; }
        public bool Enableflag { get; set; }
        public Nullable<System.DateTime> Makeupdate { get; set; }
        public string Memo { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<T_WF_Activity> T_WF_Activity { get; set; }
        public virtual ICollection<T_WF_ProcessInstance> T_WF_ProcessInstance { get; set; }
        public virtual ICollection<T_WF_RelateData> T_WF_RelateData { get; set; }
    }
}
