//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WF_Rule
    {
        public long Id { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ViewGroup { get; set; }
        public string ViewRole { get; set; }
        public string ViewEmployee { get; set; }
        public string Condition { get; set; }
        public string Execution { get; set; }
        public Nullable<long> ProcessId { get; set; }
        public Nullable<System.DateTime> ValidStartTime { get; set; }
        public Nullable<System.DateTime> ValidEndTime { get; set; }
        public Nullable<long> ExecuteStartTime { get; set; }
        public Nullable<long> ExecuteEndTime { get; set; }
        public Nullable<long> StepId { get; set; }
    }
}
