//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.CollectorTeam = new HashSet<CollectorTeam>();
        }
    
        public int Id { get; set; }
        public string Deal { get; set; }
        public string TeamName { get; set; }
        public string Description { get; set; }
        public string TeamId { get; set; }
        public string InScope { get; set; }
    
        public virtual ICollection<CollectorTeam> CollectorTeam { get; set; }
    }
}
