//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AutoSendMailInvoice
    {
        public string DEAL { get; set; }
        public string INVOICE_NUM { get; set; }
        public string INVOICE_TYPE { get; set; }
        public string CUSTOMER_NUM { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CREDIT_TREM { get; set; }
        public string MST_CUSTOMER { get; set; }
        public string PO_MUM { get; set; }
        public string SO_NUM { get; set; }
        public string CLASS { get; set; }
        public string CURRENCY { get; set; }
        public string STATES { get; set; }
        public string ORDER_BY { get; set; }
        public string BILL_GROUP_CODE { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<decimal> ORIGINAL_AMT { get; set; }
        public Nullable<decimal> BALANCE_AMT { get; set; }
        public string REMARK { get; set; }
        public string LEGAL_ENTITY { get; set; }
        public string COMMENTS { get; set; }
        public string TRACK_STATES { get; set; }
        public Nullable<System.DateTime> TRACK_DATE { get; set; }
        public Nullable<System.DateTime> PTP_DATE { get; set; }
        public string ATTENTION_TO { get; set; }
        public string COLLECTOR_CONTACT { get; set; }
        public string COLLECTOR_NAME { get; set; }
        public string CUSTOMER_ADDRESS_1 { get; set; }
        public string CUSTOMER_ADDRESS_2 { get; set; }
        public string CUSTOMER_ADDRESS_3 { get; set; }
        public string CUSTOMER_ADDRESS_4 { get; set; }
        public string CUSTOMER_BILL_TO_SITE { get; set; }
        public string CUSTOMER_COUNTRY { get; set; }
        public string CUSTOMER_COUNTRY_DETAIL { get; set; }
        public Nullable<int> DAYS_LATE_SYS { get; set; }
        public string MISS_ACCOUNT_FLG { get; set; }
        public Nullable<decimal> OUTSTANDING_ACCUMULATED_INVOICE_AMT { get; set; }
        public string RBO_CODE { get; set; }
        public Nullable<System.DateTime> STATEMENT_DATE { get; set; }
        public string SiteUseId { get; set; }
        public Nullable<decimal> CreditLmt { get; set; }
        public Nullable<decimal> CreditLmtAcct { get; set; }
        public string SellingLocationCode { get; set; }
        public string CustomerService { get; set; }
        public string LsrNameHist { get; set; }
        public string Sales { get; set; }
        public string FsrNameHist { get; set; }
        public string FuncCurrCode { get; set; }
        public Nullable<decimal> WoVat_AMT { get; set; }
        public string AgingBucket { get; set; }
        public string CreditTremDescription { get; set; }
        public string SellingLocationCode2 { get; set; }
        public string Ebname { get; set; }
        public string Customertype { get; set; }
        public string Cmpinv { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Eb { get; set; }
        public string MailId { get; set; }
        public string CallId { get; set; }
        public string Fsr { get; set; }
        public Nullable<bool> NeedTask { get; set; }
        public string FinishedStatus { get; set; }
        public Nullable<int> CollectionStrategyId { get; set; }
        public string TRACK_STATES_NAME { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> Reconciliation_Day { get; set; }
    }
}
