//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CollectionReport
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string AccntNumber { get; set; }
        public string SiteUseId { get; set; }
        public string SellingLocationCode { get; set; }
        public string CLASS { get; set; }
        public string TrxNum { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string PaymentTermName { get; set; }
        public Nullable<decimal> OverCreditLmt { get; set; }
        public Nullable<decimal> OverCreditLmtAcct { get; set; }
        public string FuncCurrCode { get; set; }
        public string InvCurrCode { get; set; }
        public string SalesName { get; set; }
        public Nullable<int> DueDays { get; set; }
        public Nullable<decimal> AmtRemaining { get; set; }
        public Nullable<decimal> AmountWoVat { get; set; }
        public string AgingBucket { get; set; }
        public string PaymentTermDesc { get; set; }
        public string SellingLocationCode2 { get; set; }
        public string Ebname { get; set; }
        public string Customertype { get; set; }
        public string Isr { get; set; }
        public string Fsr { get; set; }
        public string OrgId { get; set; }
        public string Cmpinv { get; set; }
        public string SalesOrder { get; set; }
        public string Cpo { get; set; }
        public string FsrNameHist { get; set; }
        public string isrNameHist { get; set; }
        public string Eb { get; set; }
        public string LocalName { get; set; }
        public string VatNo { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public string Collector { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<System.DateTime> Lastupdatedate { get; set; }
        public string ClearingDocument { get; set; }
        public Nullable<System.DateTime> ClearingDate { get; set; }
        public Nullable<System.DateTime> PtpIdentifiedDate { get; set; }
        public Nullable<System.DateTime> Ptpdate { get; set; }
        public string PtpBroken { get; set; }
        public string Dispute { get; set; }
        public Nullable<System.DateTime> DisputeIdentifiedDate { get; set; }
        public string DisputeReason { get; set; }
        public string ActionOwnerDepartment { get; set; }
        public string ActionOwnerName { get; set; }
        public Nullable<System.DateTime> NextActionDate { get; set; }
        public string CommentsHelpNeeded { get; set; }
    }
}
