//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DUN_COUNT
    {
        public int Id { get; set; }
        public string CUSTOMER_NUM { get; set; }
        public string SiteUseId { get; set; }
        public Nullable<int> PTP_1 { get; set; }
        public Nullable<int> PTP_2 { get; set; }
        public Nullable<int> REMINDING { get; set; }
        public Nullable<int> Dunning_1 { get; set; }
        public Nullable<int> Dunning_2 { get; set; }
        public string LEGAL_ENTITY { get; set; }
    }
}
