//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Open_AR
    {
        public int Id { get; set; }
        public Nullable<decimal> ACurrent { get; set; }
        public Nullable<decimal> B30 { get; set; }
        public Nullable<decimal> C60 { get; set; }
        public Nullable<decimal> D90 { get; set; }
        public Nullable<decimal> E120 { get; set; }
        public Nullable<decimal> F150 { get; set; }
        public Nullable<decimal> G180 { get; set; }
        public Nullable<decimal> H360 { get; set; }
        public string region { get; set; }
        public Nullable<decimal> DUEOVER360 { get; set; }
    }
}
