//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PTPVATEntry1
    {
        public int ID { get; set; }
        public Nullable<int> VatId { get; set; }
        public Nullable<int> DetailId { get; set; }
        public string InvoicePaymentTerm { get; set; }
        public string Class { get; set; }
        public string InvoiceDueDate { get; set; }
        public string PONo_ { get; set; }
        public Nullable<int> InvoiceLineNumber { get; set; }
        public string ArrowMaterialNo_ { get; set; }
        public string CustomerMaterialNo_ { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> WotPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ItemTax { get; set; }
        public Nullable<decimal> ItemWotAmount { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public string VATInvoiceDate { get; set; }
        public string VATInvoiceNo_ { get; set; }
        public Nullable<decimal> VATInvoiceWotAmount { get; set; }
        public Nullable<decimal> VATInvoiceTaxRate { get; set; }
        public string InvoiceNo_ { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<decimal> VATInvoiceAmount { get; set; }
        public string PtpDate { get; set; }
        public string dispute { get; set; }
        public string other { get; set; }
        public string IsForwarder { get; set; }
        public string Forwarder { get; set; }
        public string BalanceStatus { get; set; }
        public string BalanceMemo { get; set; }
        public string VarData1 { get; set; }
    }
}
