//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PTPPayment
    {
        public int Id { get; set; }
        public string Deal { get; set; }
        public string CustomerNum { get; set; }
        public string SiteUseId { get; set; }
        public Nullable<System.DateTime> PromiseDate { get; set; }
        public Nullable<bool> IsPartialPay { get; set; }
        public string Payer { get; set; }
        public Nullable<decimal> PromissAmount { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentBank { get; set; }
        public string MailId { get; set; }
        public string Contact { get; set; }
        public string Comments { get; set; }
        public string Tracker { get; set; }
        public string PTPPaymentType { get; set; }
        public string CollectorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string PTPStatus { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public Nullable<bool> IsForwarder { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    }
}
