//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Report_Feedback_SUM_NotBackDetail
    {
        public string Region { get; set; }
        public string COLLECTOR { get; set; }
        public string Organization { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string CREDITTREM { get; set; }
        public string CUSTOMER_NUM { get; set; }
        public string SiteUseId { get; set; }
        public string CLASS { get; set; }
        public string INVOICE_NUM { get; set; }
        public string invoice_date { get; set; }
        public string DUE_DATE { get; set; }
        public string FuncCurrCode { get; set; }
        public string currency { get; set; }
        public Nullable<int> DAYS_LATE_SYS { get; set; }
        public Nullable<decimal> BALANCE_AMT { get; set; }
        public string AgingBucket { get; set; }
        public string CreditTremDescription { get; set; }
        public string Ebname { get; set; }
        public string LsrNameHist { get; set; }
        public string FsrNameHist { get; set; }
        public string LEGAL_ENTITY { get; set; }
        public string Cmpinv { get; set; }
        public string SO_NUM { get; set; }
        public string PO_MUM { get; set; }
        public string PTP_DATE { get; set; }
        public string OverdueReason { get; set; }
        public string COMMENTS { get; set; }
        public string Status { get; set; }
        public string CloseDate { get; set; }
    }
}
