//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STATISTICS_COLLECTOR
    {
        public int Id { get; set; }
        public string COLLECTOR { get; set; }
        public Nullable<decimal> AR { get; set; }
        public Nullable<decimal> PTPAR { get; set; }
        public Nullable<decimal> PTPBROKENAR { get; set; }
        public Nullable<decimal> OVERDUEAR { get; set; }
        public Nullable<decimal> PTPAR_PER { get; set; }
        public Nullable<decimal> PTPBROKEN_PER { get; set; }
        public Nullable<decimal> OVERDUEAR_PER { get; set; }
        public Nullable<decimal> NOTREFUSEREPLY { get; set; }
        public Nullable<decimal> NOTREFUSEREPLY_PER { get; set; }
    }
}
