//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STATISTICS_COLLECT
    {
        public int Id { get; set; }
        public string CUSTOMER_NUM { get; set; }
        public string SiteUseId { get; set; }
        public Nullable<decimal> openAR { get; set; }
        public Nullable<decimal> overDure { get; set; }
        public Nullable<decimal> dispute { get; set; }
        public string Region { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string COLLECTOR { get; set; }
    }
}
