//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STATISTICS_CUSTOMER_COUNT
    {
        public string Region { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<int> m { get; set; }
        public int customerCount { get; set; }
    }
}
