//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowHistory
    {
        public int Id { get; set; }
        public string Eid { get; set; }
        public string Deal { get; set; }
        public Nullable<int> AlertId { get; set; }
        public string TaskId { get; set; }
        public string ProcessId { get; set; }
        public string CauseObjectNumber { get; set; }
        public int Type { get; set; }
    }
}
