//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelligent.OTC.Domain.DataModel
{
    using Intelligent.OTC.Common.Utils;
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkflowEntities : DbContext
    {
        private static string connectionString = string.Format(ConfigurationManager.ConnectionStrings["WorkflowEntities"].ConnectionString,
            AESUtil.AESDecrypt(ConfigurationManager.AppSettings["Workflow_Password"]));

        public WorkflowEntities()
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_WF_CurrentTask> T_WF_CurrentTask { get; set; }
        public DbSet<T_WF_ProcessInstance> T_WF_ProcessInstance { get; set; }
        public DbSet<T_WF_Activity> T_WF_Activity { get; set; }
        public DbSet<T_WF_Application> T_WF_Application { get; set; }
        public DbSet<T_WF_DetailTask> T_WF_DetailTask { get; set; }
        public DbSet<T_WF_HistoryTask> T_WF_HistoryTask { get; set; }
        public DbSet<T_WF_PostCondition> T_WF_PostCondition { get; set; }
        public DbSet<T_WF_PreCondition> T_WF_PreCondition { get; set; }
        public DbSet<T_WF_ProcessDefine> T_WF_ProcessDefine { get; set; }
        public DbSet<T_WF_RelateData> T_WF_RelateData { get; set; }
        public DbSet<T_WF_Rule> T_WF_Rule { get; set; }
        public DbSet<T_WF_Webservice> T_WF_Webservice { get; set; }
    }
}
