//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
namespace Intelligent.OTC.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    using Intelligent.OTC.Common;
    public partial class T_CollectionStrategy : IAggregateRoot
    {
    }
}
